-- Creating Employees table
CREATE TABLE Employees
(EmployeeID INT,ManagerID INT,Salary INT)

-- Inserting values into Employees table
INSERT INTO Employees (EmployeeID,Salary) VALUES
(1,100000),
(2,120000);

-- Inserting values into Employees table
INSERT INTO Employees VALUES
(3,1,100000),
(4,2,50000),
(5,1,120000),
(6,2,80000),
(7,1,100000);

-- Creating Orders table
CREATE TABLE Orders 
(OrderID INT,EmployeeID INT,CustomerID INT,Amount INT,OrderDate DATE)

-- Inserting values into Orders table
INSERT INTO Orders VALUES
(1,1,101,2000,'2026-04-05'),
(2,2,102,3000,'2026-05-06'),
(3,3,103,1500,'2026-05-08'),
(4,2,104,1600,'2026-08-06'),
(5,4,106,1700,'2026-08-08'),
(6,5,101,1800,'2026-08-12'),
(7,1,101,1500,'2026-08-15'),
(8,2,108,1600,'2026-08-16'),
(9,3,109,1900,'2026-08-19'),
(10,4,110,1850,'2026-08-14'),
(11,1,118,1600,'2026-09-01'),
(12,5,102,1700,'2026-09-18');

-- Q:-
/*
Employee Performance Analysis

Manager & Salary Comparison
For each employee, display their salary, their manager's salary, and classify the salary relationship as:
No Manager
Equal Salary
Employee Salary Greater
Employee Salary Less

Last 45 Days Order Analysis
Calculate the total number of orders handled by each employee during the last 45 days.

Last 45 Days Sales Analysis
Calculate the total sales amount generated by each employee during the last 45 days.

Total Customer Analysis
Calculate the total number of unique customers handled by each employee across all orders.

Last 45 Days Customer Analysis
Calculate the number of unique customers associated with each employee during the last 45 days and compare it with the customer count from the previous period.

Final Employee Performance Report
Combine all the above information into one employee-level report, including employees who have no orders or customers. */

-- Ans:-
WITH Last45Days AS (
SELECT
	EmployeeID,
	COUNT(*) AS TotalOrders,
	SUM(Amount) AS TotalAmount
FROM Orders
WHERE DATEDIFF(DAY,OrderDate,GETDATE()) < 45
GROUP BY EmployeeID ),

EmployeeManager AS (
SELECT
	E.EmployeeID,
	M.EmployeeID AS ManagerID,
	E.Salary AS EmployeeSalary,
	M.Salary AS ManagerSalary,
	CASE 
		WHEN M.EmployeeID IS NULL THEN 'No Manager'
		WHEN E.Salary = M.Salary THEN 'Equal Salary'
		WHEN E.Salary > M.Salary THEN 'Emplyee Salary Greater'
		WHEN E.Salary < M.Salary THEN 'Employee Salary Less'
	END AS SalaryComparision
FROM Employees AS E
LEFT JOIN Employees AS M
ON E.ManagerID = M.EmployeeID ),


Last45DaysCustomers AS (
C ),

EmployeeCustomer AS (
SELECT
	EmployeeID,
	COUNT(DISTINCT CustomerID) AS TotalCustomers
FROM Orders
GROUP BY EmployeeID)

SELECT
E.EmployeeID,
E.EmployeeSalary,
E.ManagerSalary,
E.SalaryComparision,
ISNULL(L.TotalOrders,0) AS Last45DaysTotalOrders,
ISNULL(L.TotalAmount,0) AS Last45DaysTotalAmount,
ISNULL(EC.TotalCustomers,0)AS TotalCustomers,
ISNULL(LC.TotalCustomers,0) AS Last45DaysNewCustomers
FROM EmployeeManager AS E
LEFT JOIN Last45Days AS L
ON E.EmployeeID = L.EmployeeID
LEFT JOIN Last45DaysCustomers AS LC
ON LC.EmployeeID = E.EmployeeID
LEFT JOIN EmployeeCustomer AS EC
ON EC.EmployeeID = E.EmployeeID